import { NextResponse } from 'next/server'
import { getJobsites, type Jobsite } from '@/lib/supabase'

// Mock jobsites for demo mode
const mockJobsites: Jobsite[] = [
  // NEW: Active Data Center Builds (4 sites)
  {
    id: 'mock-google-armstrong',
    name: 'Google Data Center Campus — Armstrong County',
    city: 'Claude',
    state: 'TX',
    slug: 'google-armstrong-county-tx',
    description: 'Google data center campus construction project in Armstrong County, Texas.',
    is_active: true,
    is_public: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    operator: 'Google',
    project_type: 'Data Center',
    status: 'active_build',
    county_or_parish: 'Armstrong County',
    nearest_town: 'Claude',
    notes: 'Large-scale data center campus build in the Texas Panhandle; remote-area job site near Claude.',
  },
  {
    id: 'mock-google-haskell',
    name: 'Google Data Center Projects — Haskell County',
    city: 'Haskell',
    state: 'TX',
    slug: 'google-haskell-county-tx',
    description: 'Google data center projects in Haskell County, Texas.',
    is_active: true,
    is_public: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    operator: 'Google',
    project_type: 'Data Center',
    status: 'active_build',
    county_or_parish: 'Haskell County',
    nearest_town: 'Haskell',
    notes: 'Reported multiple data center builds in Haskell County; remote West Texas job site.',
  },
  {
    id: 'mock-stargate-abilene',
    name: 'Stargate AI Data Center Site — Abilene',
    city: 'Abilene',
    state: 'TX',
    slug: 'stargate-abilene-tx',
    description: 'Stargate AI data center construction in Taylor County, Texas.',
    is_active: true,
    is_public: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    operator: 'OpenAI (Stargate)',
    project_type: 'AI Data Center',
    status: 'active_build',
    county_or_parish: 'Taylor County',
    nearest_town: 'Abilene',
    notes: 'Major AI data center construction site in Abilene area; large workforce demand during buildout.',
  },
  {
    id: 'mock-meta-richland',
    name: 'Meta Data Center Mega-Site — Richland Parish',
    city: 'Rayville',
    state: 'LA',
    slug: 'meta-richland-parish-la',
    description: 'Meta data center mega-site in Richland Parish, Louisiana.',
    is_active: true,
    is_public: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    operator: 'Meta',
    project_type: 'Data Center',
    status: 'active_build',
    county_or_parish: 'Richland Parish',
    nearest_town: 'Rayville',
    notes: 'Large Meta data center project in Northeast Louisiana; remote-area job site with substantial supporting infrastructure.',
  },
  // Existing job sites
  {
    id: 'mock-tsmc',
    name: 'TSMC Arizona',
    city: 'Phoenix',
    state: 'AZ',
    slug: 'tsmc-arizona',
    description: 'Taiwan Semiconductor Manufacturing Company fab facility.',
    is_active: true,
    is_public: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    operator: 'TSMC',
    project_type: 'Semiconductor Fab',
  },
  {
    id: 'mock-intel-az',
    name: 'Intel Ocotillo',
    city: 'Chandler',
    state: 'AZ',
    slug: 'intel-ocotillo',
    description: 'Intel semiconductor manufacturing campus.',
    is_active: true,
    is_public: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    operator: 'Intel',
    project_type: 'Semiconductor Fab',
  },
  {
    id: 'mock-samsung',
    name: 'Samsung Taylor',
    city: 'Taylor',
    state: 'TX',
    slug: 'samsung-taylor',
    description: 'Samsung semiconductor fab.',
    is_active: true,
    is_public: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    operator: 'Samsung',
    project_type: 'Semiconductor Fab',
  },
  {
    id: 'mock-ti-richardson',
    name: 'Texas Instruments Richardson',
    city: 'Richardson',
    state: 'TX',
    slug: 'ti-richardson',
    description: 'TI semiconductor facility expansion.',
    is_active: true,
    is_public: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    operator: 'Texas Instruments',
    project_type: 'Semiconductor Fab',
  },
  {
    id: 'mock-intel-oh',
    name: 'Intel Ohio',
    city: 'New Albany',
    state: 'OH',
    slug: 'intel-ohio',
    description: 'Intel mega-site semiconductor fab.',
    is_active: true,
    is_public: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    operator: 'Intel',
    project_type: 'Semiconductor Fab',
  },
  {
    id: 'mock-micron-sy',
    name: 'Micron Syracuse',
    city: 'Clay',
    state: 'NY',
    slug: 'micron-syracuse',
    description: 'Micron memory chip fab facility.',
    is_active: true,
    is_public: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    operator: 'Micron',
    project_type: 'Semiconductor Fab',
  },
  {
    id: 'mock-micron-bo',
    name: 'Micron Boise',
    city: 'Boise',
    state: 'ID',
    slug: 'micron-boise',
    description: 'Micron Technology headquarters and fab.',
    is_active: true,
    is_public: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    operator: 'Micron',
    project_type: 'Semiconductor Fab',
  },
  {
    id: 'mock-tesla',
    name: 'Tesla Gigafactory Texas',
    city: 'Austin',
    state: 'TX',
    slug: 'tesla-gigafactory-texas',
    description: 'Tesla vehicle and battery manufacturing.',
    is_active: true,
    is_public: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    operator: 'Tesla',
    project_type: 'Manufacturing',
  },
  {
    id: 'mock-aws',
    name: 'AWS Data Center Ashburn',
    city: 'Ashburn',
    state: 'VA',
    slug: 'aws-ashburn',
    description: 'Amazon Web Services data center campus.',
    is_active: true,
    is_public: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    operator: 'AWS',
    project_type: 'Data Center',
  },
  {
    id: 'mock-microsoft-va',
    name: 'Microsoft Boydton',
    city: 'Boydton',
    state: 'VA',
    slug: 'microsoft-boydton',
    description: 'Microsoft Azure data center campus.',
    is_active: true,
    is_public: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    operator: 'Microsoft',
    project_type: 'Data Center',
  },
]

export async function GET() {
  try {
    // If Supabase not configured, return mock data
    if (!process.env.NEXT_PUBLIC_SUPABASE_URL || !process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY) {
      return NextResponse.json(mockJobsites)
    }

    const jobsites = await getJobsites()
    return NextResponse.json(jobsites)
  } catch (error) {
    console.error('Jobsites fetch error:', error)
    // Return mock data on error
    return NextResponse.json(mockJobsites)
  }
}
